"""
Build the bundled guardrail catalog (app/data/guardrails/azure_guardrails.json).

The catalog is a curated set of security controls derived from public guidance:
- Azure: the Microsoft Cloud Security Benchmark (MCSB) and built-in Azure Policy
  definitions (CONTROLS).
- AWS: AWS Foundational Security Best Practices (FSBP) and AWS Config managed
  rules (AWS_CONTROLS).
Each control maps a cloud service (see service_map.json) to a recommendation,
the risk it mitigates, the benchmark control it implements and the policy/rule
that audits it.

Contributing a control: add a tuple to CONTROLS or AWS_CONTROLS below, then run

    python scripts/build_guardrail_catalog.py

and commit the regenerated JSON. Keep the `service` value identical to a key in
app/data/guardrails/service_map.json, otherwise the control never matches.

Tuple layout:
    (control_id, service, severity, theme, benchmark, policy,
     recommendation, risk)
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "app" / "data" / "guardrails" / "azure_guardrails.json"
SERVICE_MAP = OUT.parent / "service_map.json"

CONTROLS = [
    # ------------------------------------------------------------------ Storage
    ("LFT-STG-01", "Storage Account", "High", "Data Protection", "DP-3",
     "Secure transfer to storage accounts should be enabled",
     "Enable secure transfer (supportsHttpsTrafficOnly: true) so the account only accepts HTTPS requests.",
     "Plain HTTP requests expose data and shared keys to interception in transit."),
    ("LFT-STG-02", "Storage Account", "High", "Public Access", "DP-2",
     "Storage account public access should be disallowed",
     "Disable anonymous public blob access (allowBlobPublicAccess: false) on the account.",
     "Anonymous containers let anyone on the internet list and read blob data."),
    ("LFT-STG-03", "Storage Account", "Medium", "Data Protection", "DP-3",
     "Storage accounts should have the specified minimum TLS version",
     "Require TLS 1.2 or later (minimumTlsVersion: 'TLS1_2').",
     "Legacy TLS 1.0/1.1 protocols have known weaknesses that allow downgrade and decryption attacks."),
    ("LFT-STG-04", "Storage Account", "High", "Network Security", "NS-2",
     "Storage accounts should disable public network access",
     "Disable public network access and set networkAcls defaultAction to 'Deny'; reach the account through a private endpoint or selected virtual networks, allowing trusted Microsoft services.",
     "A storage endpoint reachable from any network widens the attack surface for credential stuffing and data exfiltration."),
    ("LFT-STG-05", "Storage Account", "Medium", "Data Protection", "DP-4",
     "Storage accounts should use customer-managed key for encryption",
     "Keep storage service encryption (SSE) for encryption at rest enabled; use customer-managed keys in Key Vault when regulation requires key custody.",
     "Without controlled encryption at rest, compromised media or backups could expose data."),
    ("LFT-STG-06", "Storage Account", "Medium", "Identity", "IM-1",
     "Storage accounts should prevent shared key access",
     "Disable shared key authorization (allowSharedKeyAccess: false) and use Microsoft Entra ID with RBAC for data access.",
     "Account keys grant full, non-attributable access and are frequently leaked in code and config."),
    ("LFT-STG-07", "Storage Account", "Low", "Data Protection", "BR-1",
     "Soft delete should be enabled for blobs and containers",
     "Enable blob and container soft delete with a retention period of at least 7 days.",
     "Accidental or malicious deletion becomes unrecoverable."),

    # ------------------------------------------------------------------ Key Vault
    ("LFT-KV-01", "Key Vault", "High", "Data Protection", "DP-8",
     "Key vaults should have deletion protection enabled",
     "Enable purge protection (enablePurgeProtection: true) so deleted vaults and secrets cannot be permanently purged during the retention period.",
     "An attacker or mistake could permanently destroy keys, making encrypted data unrecoverable."),
    ("LFT-KV-02", "Key Vault", "Medium", "Data Protection", "DP-8",
     "Key vaults should have soft delete enabled",
     "Keep soft delete enabled with softDeleteRetentionInDays set (90 recommended).",
     "Deleted secrets, keys and certificates cannot be recovered."),
    ("LFT-KV-03", "Key Vault", "High", "Network Security", "NS-2",
     "Azure Key Vault should disable public network access",
     "Restrict the vault to private networks: publicNetworkAccess 'Disabled' with a private link endpoint, or networkAcls defaultAction 'Deny' with trusted service bypass.",
     "A vault reachable from the public internet is exposed to brute-force and token replay attempts."),
    ("LFT-KV-04", "Key Vault", "Medium", "Identity", "PA-7",
     "Azure Key Vault should use RBAC permission model",
     "Use the Azure RBAC permission model (enableRbacAuthorization: true) instead of vault access policies.",
     "Access policies are coarse-grained and bypass central RBAC governance and PIM."),
    ("LFT-KV-05", "Key Vault", "Medium", "Logging", "LT-3",
     "Resource logs in Key Vault should be enabled",
     "Send AuditEvent logs to a Log Analytics workspace through diagnostic settings.",
     "Secret access cannot be investigated after an incident."),
    ("LFT-KV-06", "Key Vault", "Low", "Data Protection", "DP-6",
     "Key Vault secrets should have an expiration date",
     "Set expiration dates on secrets and keys and rotate them before expiry.",
     "Long-lived secrets increase the blast radius of a leak."),

    # ------------------------------------------------------------------ App Service / Functions
    ("LFT-WEB-01", "App Service", "High", "Data Protection", "DP-3",
     "App Service apps should only be accessible over HTTPS",
     "Set httpsOnly: true so HTTP requests are redirected to HTTPS.",
     "Traffic over plain HTTP can be intercepted or modified."),
    ("LFT-WEB-02", "App Service", "Medium", "Data Protection", "DP-3",
     "App Service apps should use the latest TLS version",
     "Require TLS 1.2 or later (siteConfig.minTlsVersion: '1.2').",
     "Older TLS versions are vulnerable to protocol downgrade attacks."),
    ("LFT-WEB-03", "App Service", "High", "Network Security", "NS-2",
     "App Service apps should disable public network access",
     "Disable public network access for internal apps and front them with a private endpoint, Application Gateway or Front Door.",
     "Internal workloads exposed to the internet invite scanning and exploitation."),
    ("LFT-WEB-04", "App Service", "Medium", "Identity", "IM-3",
     "App Service apps should use managed identity",
     "Enable a managed identity and use it to reach Key Vault, Storage and databases instead of connection strings.",
     "Embedded credentials leak through app settings, logs and source control."),
    ("LFT-WEB-05", "App Service", "Medium", "Posture", "PV-2",
     "FTPS only should be required in App Service apps",
     "Disable FTP deployment (siteConfig.ftpsState: 'Disabled' or 'FtpsOnly').",
     "FTP sends deployment credentials in clear text."),
    ("LFT-WEB-06", "App Service", "Low", "Posture", "PV-2",
     "App Service apps should have remote debugging turned off",
     "Keep remote debugging disabled outside of short troubleshooting windows.",
     "Remote debugging opens additional inbound ports on the worker."),
    ("LFT-FUNC-01", "Function App", "High", "Data Protection", "DP-3",
     "Function apps should only be accessible over HTTPS",
     "Set httpsOnly: true on the function app.",
     "Function triggers over HTTP expose payloads and function keys."),
    ("LFT-FUNC-02", "Function App", "Medium", "Data Protection", "DP-3",
     "Function apps should use the latest TLS version",
     "Require TLS 1.2 or later (siteConfig.minTlsVersion: '1.2').",
     "Older TLS versions are vulnerable to protocol downgrade attacks."),
    ("LFT-FUNC-03", "Function App", "High", "Network Security", "NS-2",
     "Function apps should disable public network access",
     "Disable public network access for internal functions and integrate the app with a virtual network.",
     "Publicly reachable function endpoints can be invoked or abused by anyone holding a leaked key."),
    ("LFT-FUNC-04", "Function App", "Medium", "Identity", "IM-3",
     "Function apps should use managed identity",
     "Use a managed identity for the AzureWebJobsStorage connection and downstream services (identity-based connections).",
     "Storage account keys in app settings grant full account access if leaked."),

    # ------------------------------------------------------------------ SQL
    ("LFT-SQL-01", "SQL Database", "High", "Network Security", "NS-2",
     "Public network access on Azure SQL Database should be disabled",
     "Disable public network access (publicNetworkAccess: 'Disabled') and connect through a private endpoint.",
     "Internet-exposed SQL endpoints are continuously targeted by password spraying."),
    ("LFT-SQL-02", "SQL Database", "High", "Identity", "IM-1",
     "Azure SQL Database should have Microsoft Entra-only authentication enabled",
     "Enable Microsoft Entra-only authentication and use managed identities for applications.",
     "SQL logins are shared secrets that bypass MFA and conditional access."),
    ("LFT-SQL-03", "SQL Database", "Medium", "Data Protection", "DP-3",
     "Azure SQL Database should be running TLS version 1.2 or newer",
     "Set minimalTlsVersion to '1.2'.",
     "Older TLS versions are vulnerable to downgrade attacks."),
    ("LFT-SQL-04", "SQL Database", "Medium", "Logging", "LT-3",
     "Auditing on SQL server should be enabled",
     "Enable server auditing to a Log Analytics workspace or storage account.",
     "Database access and schema changes cannot be traced."),
    ("LFT-SQL-05", "SQL Database", "Medium", "Data Protection", "DP-4",
     "Transparent Data Encryption on SQL databases should be enabled",
     "Keep Transparent Data Encryption enabled for encryption at rest.",
     "Database files and backups could be read if storage media is compromised."),
    ("LFT-SQLMI-01", "SQL Managed Instance", "High", "Network Security", "NS-2",
     "Azure SQL Managed Instances should disable public network access",
     "Keep the public data endpoint disabled and connect over the virtual network or a private endpoint.",
     "The public endpoint exposes the instance to internet-based attacks."),
    ("LFT-SQLMI-02", "SQL Managed Instance", "High", "Identity", "IM-1",
     "Azure SQL Managed Instance should have Microsoft Entra-only authentication enabled",
     "Enable Microsoft Entra-only authentication.",
     "SQL logins are shared secrets that bypass MFA."),

    # ------------------------------------------------------------------ Cosmos DB
    ("LFT-COS-01", "Cosmos DB", "High", "Network Security", "NS-2",
     "Azure Cosmos DB should disable public network access",
     "Disable public network access (publicNetworkAccess: 'Disabled') and use a private endpoint.",
     "Internet-reachable accounts are exposed to key abuse and data exfiltration."),
    ("LFT-COS-02", "Cosmos DB", "High", "Identity", "IM-1",
     "Cosmos DB database accounts should have local authentication methods disabled",
     "Disable key-based auth (disableLocalAuth: true) and use Entra ID with Cosmos DB data-plane RBAC.",
     "Primary keys grant full, non-attributable access to all data."),
    ("LFT-COS-03", "Cosmos DB", "Low", "Data Protection", "BR-1",
     "Azure Cosmos DB accounts should use continuous backup",
     "Use continuous backup mode for point-in-time restore.",
     "Periodic backups may lose hours of data after corruption or deletion."),

    # ------------------------------------------------------------------ PostgreSQL / MySQL
    ("LFT-PG-01", "Database for PostgreSQL Flexible Server", "High", "Network Security", "NS-2",
     "Public network access should be disabled for PostgreSQL flexible servers",
     "Deploy with private access (VNet integration) or disable public network access and use a private endpoint.",
     "Publicly reachable database servers are exposed to credential attacks."),
    ("LFT-PG-02", "Database for PostgreSQL Flexible Server", "Medium", "Data Protection", "DP-3",
     "Enforce SSL connection should be enabled for PostgreSQL flexible servers",
     "Require secure transport (require_secure_transport = ON) with TLS 1.2 or later.",
     "Unencrypted database connections leak credentials and query data."),
    ("LFT-PG-03", "Database for PostgreSQL Flexible Server", "Medium", "Identity", "IM-1",
     "PostgreSQL flexible servers should use Microsoft Entra authentication",
     "Enable Microsoft Entra authentication and prefer managed identities for applications.",
     "Password-only authentication cannot enforce MFA or central revocation."),
    ("LFT-PG-04", "Database for PostgreSQL", "High", "Posture", "PV-5",
     "Azure Database for PostgreSQL single server is retired",
     "Migrate single-server deployments to Azure Database for PostgreSQL flexible server.",
     "Single server is retired and no longer receives security updates."),
    ("LFT-MY-01", "Database for MySQL Flexible Server", "High", "Network Security", "NS-2",
     "Public network access should be disabled for MySQL flexible servers",
     "Deploy with private access (VNet integration) or disable public network access and use a private endpoint.",
     "Publicly reachable database servers are exposed to credential attacks."),
    ("LFT-MY-02", "Database for MySQL Flexible Server", "Medium", "Data Protection", "DP-3",
     "MySQL servers should enforce TLS 1.2",
     "Require secure transport and set tls_version to TLSv1.2 or later.",
     "Unencrypted database connections leak credentials and query data."),
    ("LFT-MY-03", "Database for MySQL", "High", "Posture", "PV-5",
     "Azure Database for MySQL single server is retired",
     "Migrate single-server deployments to Azure Database for MySQL flexible server.",
     "Single server is retired and no longer receives security updates."),

    # ------------------------------------------------------------------ AI services
    ("LFT-AI-01", "AI Services", "High", "Network Security", "NS-2",
     "Azure AI Services resources should restrict network access",
     "Disable public network access (publicNetworkAccess: 'Disabled') and use a private endpoint, or set networkAcls defaultAction 'Deny'.",
     "Model endpoints reachable from the internet can be abused for data exfiltration and cost attacks."),
    ("LFT-AI-02", "AI Services", "High", "Identity", "IM-1",
     "Azure AI Services resources should have key access disabled",
     "Disable local (key) authentication (disableLocalAuth: true) and use Microsoft Entra ID.",
     "API keys are long-lived shared secrets and are frequently leaked."),
    ("LFT-AI-03", "OpenAI", "High", "Network Security", "NS-2",
     "Azure OpenAI resources should restrict network access",
     "Disable public network access (publicNetworkAccess: 'Disabled') and reach the endpoint through a private endpoint.",
     "Publicly reachable model endpoints can be abused with leaked keys."),
    ("LFT-AI-04", "OpenAI", "High", "Identity", "IM-1",
     "Azure OpenAI resources should have key access disabled",
     "Set disableLocalAuth: true and grant applications the 'Cognitive Services OpenAI User' role through managed identity.",
     "API keys bypass identity-based access control and auditing."),
    ("LFT-AI-05", "Azure AI Foundry", "Medium", "Network Security", "NS-2",
     "Azure AI Foundry hubs and projects should use private link",
     "Configure the hub with a managed virtual network (isolation mode) and private endpoints.",
     "Model, data and prompt traffic is exposed on public endpoints."),
    ("LFT-AI-06", "Azure AI Foundry", "Medium", "Logging", "LT-3",
     "Resource logs in Azure AI services should be enabled",
     "Send audit and request logs to a Log Analytics workspace.",
     "Prompt abuse and data access cannot be investigated."),
    ("LFT-ML-01", "Machine Learning", "Medium", "Network Security", "NS-2",
     "Azure Machine Learning workspaces should disable public network access",
     "Disable public network access and use private endpoints with a managed virtual network.",
     "Workspace APIs and datastores are exposed to the internet."),
    ("LFT-ML-02", "Machine Learning", "Medium", "Identity", "IM-1",
     "Azure Machine Learning computes should have local authentication disabled",
     "Disable local authentication on compute and use Microsoft Entra ID.",
     "Local credentials on compute bypass central identity controls."),

    # ------------------------------------------------------------------ Compute
    ("LFT-VM-01", "Virtual Machine", "High", "Network Security", "NS-1",
     "Management ports should be closed on your virtual machines",
     "Do not expose RDP (3389) or SSH (22) to the internet; use Azure Bastion or just-in-time VM access.",
     "Exposed management ports are brute-forced within minutes of deployment."),
    ("LFT-VM-02", "Virtual Machine", "Medium", "Data Protection", "DP-4",
     "Virtual machines should enable encryption at host",
     "Enable encryption at host so temp disks and caches are encrypted at rest.",
     "Temporary disks and caches could hold unencrypted data."),
    ("LFT-VM-03", "Virtual Machine", "Medium", "Posture", "PV-6",
     "Machines should be configured to periodically check for missing system updates",
     "Enable Azure Update Manager periodic assessment and automatic guest patching.",
     "Unpatched operating systems are the most common path to compromise."),
    ("LFT-VM-04", "Virtual Machine", "Medium", "Identity", "IM-3",
     "Virtual machines should use managed identity",
     "Assign a managed identity instead of storing credentials on the machine.",
     "Credentials stored on disk can be harvested after a compromise."),
    ("LFT-VM-05", "Virtual Machine", "Medium", "Endpoint Security", "ES-1",
     "Endpoint protection should be installed on your machines",
     "Onboard machines to Microsoft Defender for Servers or an equivalent EDR solution.",
     "Malware and intrusions go undetected."),
    ("LFT-VMSS-01", "Virtual Machine Scale Set", "Medium", "Posture", "PV-6",
     "Virtual machine scale sets should have automatic OS upgrades enabled",
     "Enable automatic OS image upgrades and health probes.",
     "Instances drift out of patch compliance."),
    ("LFT-VMSS-02", "Virtual Machine Scale Set", "High", "Network Security", "NS-1",
     "Management ports should be closed on virtual machine scale sets",
     "Do not expose RDP or SSH on the scale set load balancer; use Azure Bastion.",
     "Exposed management ports are brute-forced."),
    ("LFT-DISK-01", "Disks", "Medium", "Network Security", "NS-2",
     "Managed disks should disable public network access",
     "Set publicNetworkAccess 'Disabled' and networkAccessPolicy 'DenyAll' or 'AllowPrivate'.",
     "Disk export SAS URLs can be generated and downloaded from anywhere."),
    ("LFT-DISK-02", "Disks", "Low", "Data Protection", "DP-4",
     "Managed disks should be double encrypted with platform-managed and customer-managed keys",
     "Use a disk encryption set with customer-managed keys when regulation requires key custody.",
     "Platform-managed keys may not meet regulatory key-custody requirements."),
    ("LFT-BATCH-01", "Batch Accounts", "Medium", "Network Security", "NS-2",
     "Azure Batch accounts should disable public network access",
     "Disable public network access and use private endpoints.",
     "Batch account endpoints are exposed to the internet."),
    ("LFT-BATCH-02", "Batch Accounts", "Medium", "Identity", "IM-1",
     "Azure Batch accounts should disable local authentication",
     "Allow only Microsoft Entra authentication (allowedAuthenticationModes: ['AAD']).",
     "Shared keys grant full account access."),

    # ------------------------------------------------------------------ Containers
    ("LFT-AKS-01", "Kubernetes Services", "High", "Network Security", "NS-2",
     "Azure Kubernetes Service private clusters should be enabled",
     "Use a private cluster, or restrict the API server with authorized IP ranges.",
     "A public API server is exposed to credential and vulnerability attacks."),
    ("LFT-AKS-02", "Kubernetes Services", "High", "Identity", "IM-1",
     "Azure Kubernetes Service clusters should have local authentication methods disabled",
     "Disable local accounts (disableLocalAccounts: true) and enable Microsoft Entra integration with Azure RBAC.",
     "Static cluster-admin certificates cannot be revoked individually."),
    ("LFT-AKS-03", "Kubernetes Services", "Medium", "Posture", "PV-2",
     "Azure Policy Add-on for Kubernetes service should be installed and enabled",
     "Enable the Azure Policy add-on and apply the pod security baseline.",
     "Privileged or misconfigured pods can compromise the node."),
    ("LFT-AKS-04", "Kubernetes Services", "Medium", "Network Security", "NS-1",
     "Kubernetes clusters should use network policies",
     "Enable a network policy engine (Azure, Calico or Cilium) and default-deny namespace traffic.",
     "Flat pod networking allows lateral movement after a pod compromise."),
    ("LFT-AKS-05", "Kubernetes Services", "Medium", "Posture", "PV-6",
     "Kubernetes Services should be upgraded to a non-vulnerable Kubernetes version",
     "Enable an automatic upgrade channel ('patch' or 'stable') and node OS auto-upgrade.",
     "Clusters on unsupported versions miss security fixes."),
    ("LFT-ACR-01", "Container Registry", "High", "Network Security", "NS-2",
     "Container registries should not allow unrestricted network access",
     "Disable public network access on Premium registries and use private endpoints.",
     "Images and pull tokens are exposed to the internet."),
    ("LFT-ACR-02", "Container Registry", "High", "Identity", "IM-1",
     "Container registries should have the admin user disabled",
     "Set adminUserEnabled: false and pull with managed identity (AcrPull role).",
     "The admin user is a shared credential with push and pull rights."),
    ("LFT-ACR-03", "Container Registry", "Medium", "Identity", "IM-1",
     "Container registries should have anonymous authentication disabled",
     "Keep anonymous pull disabled (anonymousPullEnabled: false).",
     "Anyone can pull proprietary images."),

    # ------------------------------------------------------------------ Networking
    ("LFT-NSG-01", "Network Security Group", "High", "Network Security", "NS-1",
     "Network security groups should not allow inbound management traffic from the internet",
     "Deny inbound RDP (3389) and SSH (22) from 'Internet' or '*' sources.",
     "Open management ports are brute-forced continuously."),
    ("LFT-NSG-02", "Network Security Group", "Medium", "Network Security", "NS-1",
     "All network ports should be restricted on network security groups",
     "Avoid 'Any' source rules; scope inbound rules to specific ports and source prefixes.",
     "Overly permissive rules expose services that were meant to be internal."),
    ("LFT-NSG-03", "Network Security Group", "Low", "Logging", "LT-4",
     "Flow logs should be configured for every virtual network",
     "Enable virtual network flow logs with traffic analytics.",
     "Network-level investigations lack evidence."),
    ("LFT-VNET-01", "Virtual Network", "Medium", "Network Security", "NS-1",
     "Subnets should be associated with a network security group",
     "Associate a network security group with every workload subnet.",
     "Subnets without an NSG allow unfiltered lateral traffic."),
    ("LFT-VNET-02", "Virtual Network", "Medium", "Network Security", "NS-5",
     "Azure DDoS Protection should be enabled",
     "Enable DDoS Network Protection for virtual networks that host internet-facing workloads.",
     "Volumetric attacks can take public endpoints offline."),
    ("LFT-VNET-03", "Virtual Network", "Low", "Network Security", "NS-2",
     "Subnets should be private",
     "Disable default outbound access (defaultOutboundAccess: false) and use NAT Gateway or a firewall for egress.",
     "Implicit outbound IPs make egress hard to control and audit."),
    ("LFT-NIC-01", "Network Interface", "Medium", "Network Security", "NS-1",
     "Network interfaces should not have public IPs",
     "Do not attach public IP addresses directly to NICs; publish through a load balancer, gateway or Bastion.",
     "Directly exposed VMs bypass centralized perimeter controls."),
    ("LFT-PIP-01", "Public IP Address", "Medium", "Network Security", "NS-5",
     "Public IP addresses should have resource logs enabled for Azure DDoS Protection",
     "Use Standard SKU public IPs, zone-redundant where available, protected by DDoS Network Protection.",
     "Basic SKU public IPs are retired and lack DDoS telemetry."),
    ("LFT-AGW-01", "Application Gateway", "High", "Network Security", "NS-6",
     "Web Application Firewall (WAF) should be enabled for Application Gateway",
     "Use the WAF_v2 SKU with a WAF policy in Prevention mode.",
     "Web apps are exposed to OWASP Top 10 attacks."),
    ("LFT-AGW-02", "Application Gateway", "Medium", "Data Protection", "DP-3",
     "Application Gateway should use a TLS policy that requires TLS 1.2",
     "Use a predefined TLS policy of AppGwSslPolicy20220101 or newer.",
     "Weak ciphers allow downgrade and decryption attacks."),
    ("LFT-LB-01", "Load Balancer", "Low", "Posture", "PV-2",
     "Load balancers should use the Standard SKU",
     "Use the Standard SKU; Basic load balancers are retired.",
     "Basic SKU is retired and lacks secure-by-default behaviour."),
    ("LFT-DNS-01", "Domain Name Service", "Low", "Posture", "PV-2",
     "DNS zones should be protected against deletion",
     "Apply a CanNotDelete resource lock to production DNS zones.",
     "Accidental deletion causes outages and enables subdomain takeover."),
    ("LFT-APIM-01", "API Management", "High", "Network Security", "NS-2",
     "API Management services should use a virtual network",
     "Deploy in internal VNet mode or disable public network access, publishing through Application Gateway with WAF.",
     "Backend APIs are exposed without a perimeter."),
    ("LFT-APIM-02", "API Management", "Medium", "Data Protection", "DP-3",
     "API Management should disable insecure protocols and ciphers",
     "Disable TLS 1.0/1.1, SSL 3.0 and 3DES in customProperties.",
     "Legacy protocols allow interception."),
    ("LFT-APIM-03", "API Management", "Medium", "Identity", "IM-3",
     "API Management secret named values should be stored in Azure Key Vault",
     "Use Key Vault-backed named values accessed through managed identity.",
     "Secrets stored inline in APIM are hard to rotate and audit."),

    # ------------------------------------------------------------------ Integration / data
    ("LFT-SB-01", "Service Bus", "Medium", "Identity", "IM-1",
     "Azure Service Bus namespaces should have local authentication methods disabled",
     "Set disableLocalAuth: true and use Entra ID RBAC (Azure Service Bus Data Sender/Receiver).",
     "SAS keys are shared secrets with broad rights."),
    ("LFT-SB-02", "Service Bus", "Medium", "Network Security", "NS-2",
     "Service Bus namespaces should disable public network access",
     "Disable public network access on Premium namespaces and use private endpoints.",
     "Messaging endpoints are exposed to the internet."),
    ("LFT-ADF-01", "Data Factory", "Medium", "Network Security", "NS-2",
     "Azure Data Factory should disable public network access",
     "Disable public network access and use a managed virtual network with managed private endpoints.",
     "Pipelines and linked services are reachable from the internet."),
    ("LFT-ADF-02", "Data Factory", "Medium", "Identity", "IM-3",
     "Azure Data Factory linked services should use Key Vault for storing secrets",
     "Reference credentials from Key Vault or use managed identity authentication.",
     "Inline secrets in linked services leak through exports."),
    ("LFT-DBW-01", "Databricks", "Medium", "Network Security", "NS-2",
     "Azure Databricks workspaces should disable public network access",
     "Use VNet injection with secure cluster connectivity (no public IP) and private link.",
     "Workspace and cluster endpoints are exposed publicly."),
    ("LFT-LOGIC-01", "Logic Apps", "Medium", "Identity", "IM-3",
     "Logic Apps should use managed identity for connections",
     "Authenticate connectors and HTTP actions with managed identity; secure trigger inputs and outputs.",
     "Connection secrets and run history can expose credentials."),
    ("LFT-REDIS-01", "Cache for Redis", "High", "Data Protection", "DP-3",
     "Azure Cache for Redis should only allow secure connections",
     "Disable the non-SSL port (enableNonSslPort: false) and require TLS 1.2.",
     "Cache data and access keys travel unencrypted."),
    ("LFT-REDIS-02", "Cache for Redis", "Medium", "Network Security", "NS-2",
     "Azure Cache for Redis should disable public network access",
     "Disable public network access and use a private endpoint.",
     "Cache endpoints are exposed to the internet."),
    ("LFT-AUTO-01", "Automation Accounts", "Medium", "Identity", "IM-3",
     "Automation accounts should use managed identity",
     "Use a managed identity instead of Run As accounts; encrypt variables.",
     "Certificates and variables can leak credentials."),

    # ------------------------------------------------------------------ Monitoring
    ("LFT-APPI-01", "Application Insights", "Low", "Identity", "IM-1",
     "Application Insights components should block non-Entra ID based ingestion",
     "Disable local authentication (DisableLocalAuth: true) so telemetry ingestion requires Entra ID.",
     "Anyone with the connection string can inject fake telemetry."),
    ("LFT-APPI-02", "Application Insights", "Low", "Logging", "LT-5",
     "Application Insights components should be workspace-based",
     "Link the component to a Log Analytics workspace (WorkspaceResourceId).",
     "Classic components are retired and cannot be governed centrally."),
    ("LFT-MON-01", "Monitor", "Medium", "Logging", "LT-4",
     "Activity log should be retained for at least one year",
     "Export the subscription activity log to a Log Analytics workspace with adequate retention.",
     "Control-plane changes cannot be investigated after the default 90 days."),

    # ------------------------------------------------------------------ Environment scope
    ("LFT-ENV-01", "Entra ID", "Critical", "Identity", "IM-6",
     "Accounts with owner permissions on Azure resources should be MFA enabled",
     "Require multi-factor authentication for all users through Conditional Access.",
     "Password-only accounts are easily phished or sprayed."),
    ("LFT-ENV-02", "Entra ID", "High", "Identity", "IM-7",
     "Conditional Access should block legacy authentication",
     "Block legacy authentication protocols tenant-wide.",
     "Legacy protocols cannot enforce MFA."),
    ("LFT-ENV-03", "Entra ID", "High", "Privileged Access", "PA-2",
     "Privileged roles should use just-in-time access",
     "Use Privileged Identity Management for eligible, time-bound role activation.",
     "Standing privileged access increases the impact of a compromised account."),
    ("LFT-ENV-04", "Identity and Access Management", "High", "Privileged Access", "PA-1",
     "A maximum of 3 owners should be designated for your subscription",
     "Keep subscription owners to a small, reviewed group (between 2 and 3).",
     "Too many owners widens the privileged attack surface."),
    ("LFT-ENV-05", "Identity and Access Management", "Medium", "Privileged Access", "PA-7",
     "Guest accounts with owner permissions on Azure resources should be removed",
     "Remove guest and external accounts from privileged roles and review access regularly.",
     "External identities are outside your lifecycle and MFA controls."),
    ("LFT-ENV-06", "Identity and Access Management", "Medium", "Privileged Access", "PA-7",
     "Custom subscription owner roles should not exist",
     "Prefer built-in least-privilege roles; avoid wildcard custom roles.",
     "Custom wildcard roles silently grant owner-equivalent rights."),
    ("LFT-ENV-07", "Subscription", "Medium", "Logging", "LT-1",
     "Subscriptions should have a contact email address for security issues",
     "Configure security contact details and alert notifications in Defender for Cloud.",
     "Security alerts go unnoticed."),
    ("LFT-ENV-08", "Subscription", "Medium", "Governance", "AM-2",
     "Require a tag on resources",
     "Enforce tags such as environment, owner and cost-center with Azure Policy.",
     "Untagged resources cannot be attributed, costed or cleaned up."),
    ("LFT-ENV-09", "Subscription", "Medium", "Governance", "AM-2",
     "Allowed locations",
     "Restrict deployments to approved regions with Azure Policy.",
     "Data residency obligations can be breached."),
    ("LFT-ENV-10", "Defender for cloud", "High", "Posture", "LT-1",
     "Microsoft Defender for Cloud plans should be enabled",
     "Enable Defender CSPM and the workload plans (Servers, Storage, Key Vault, Databases, Containers) that match your estate.",
     "Threats and misconfigurations are not detected."),
    ("LFT-ENV-11", "Defender for cloud", "Medium", "Posture", "PV-1",
     "Microsoft cloud security benchmark initiative should be assigned",
     "Assign the Microsoft cloud security benchmark policy initiative at management group scope.",
     "Continuous compliance drift goes unmeasured."),
    ("LFT-ENV-12", "Subscription Feature", "Low", "Governance", "AM-1",
     "Resource providers should be registered deliberately",
     "Register only the resource providers you need and review preview features before enabling them.",
     "Unreviewed preview features may not meet security and support requirements."),
]

# AWS controls. `benchmark` is the AWS Foundational Security Best Practices (FSBP)
# control ID; `policy` is the AWS Config managed rule that evaluates it (empty
# when no single managed rule applies).
AWS_CONTROLS = [
    # ------------------------------------------------------------------ S3
    ("LFT-AWS-S3-01", "Amazon S3", "Critical", "Public Access", "S3.8",
     "s3-bucket-level-public-access-prohibited",
     "Block public access on every bucket: BlockPublicAcls, BlockPublicPolicy, IgnorePublicAcls and RestrictPublicBuckets all true.",
     "A bucket reachable by anonymous users leaks data and is the most common cause of cloud data breaches."),
    ("LFT-AWS-S3-02", "Amazon S3", "High", "Data Protection", "S3.17",
     "s3-default-encryption-kms",
     "Encrypt objects at rest with default bucket encryption (SSE-KMS, or SSE-S3 at minimum).",
     "Unencrypted objects are exposed if storage media or backups are compromised."),
    ("LFT-AWS-S3-03", "Amazon S3", "Medium", "Data Protection", "S3.5",
     "s3-bucket-ssl-requests-only",
     "Require TLS: add a bucket policy that denies requests where aws:SecureTransport is false (SSL-only).",
     "Plain HTTP requests expose object data and credentials in transit."),
    ("LFT-AWS-S3-04", "Amazon S3", "Low", "Data Protection", "S3.14",
     "s3-bucket-versioning-enabled",
     "Enable versioning so overwritten or deleted objects can be recovered.",
     "Accidental or malicious deletion becomes unrecoverable."),
    ("LFT-AWS-S3-05", "Amazon S3", "Medium", "Logging", "S3.9",
     "s3-bucket-logging-enabled",
     "Enable server access logging to a separate logging bucket.",
     "Access to sensitive objects cannot be investigated after an incident."),

    # ------------------------------------------------------------------ RDS
    ("LFT-AWS-RDS-01", "Amazon RDS", "Critical", "Public Access", "RDS.2",
     "rds-instance-public-access-check",
     "Keep database instances private: PubliclyAccessible false, reachable only from inside the VPC.",
     "Internet-reachable databases are targeted by credential attacks within minutes."),
    ("LFT-AWS-RDS-02", "Amazon RDS", "High", "Data Protection", "RDS.3",
     "rds-storage-encrypted",
     "Encrypt storage at rest (StorageEncrypted true) with a KMS key.",
     "Snapshots and storage of unencrypted databases can be read if copied or leaked."),
    ("LFT-AWS-RDS-03", "Amazon RDS", "Medium", "Resilience", "RDS.5",
     "rds-multi-az-support",
     "Deploy production instances Multi-AZ.",
     "A single Availability Zone failure takes the database offline."),
    ("LFT-AWS-RDS-04", "Amazon RDS", "Low", "Resilience", "RDS.8",
     "rds-instance-deletion-protection-enabled",
     "Enable deletion protection on production instances.",
     "A mistaken stack update or console action can delete the database."),

    # ------------------------------------------------------------------ EC2 / VPC
    ("LFT-AWS-EC2-01", "Amazon EC2", "High", "Identity", "EC2.8",
     "ec2-imdsv2-check",
     "Require IMDSv2 for the instance metadata service (HttpTokens required).",
     "IMDSv1 lets server-side request forgery steal the instance role's credentials."),
    ("LFT-AWS-EC2-02", "Amazon EC2", "High", "Network Security", "EC2.9",
     "ec2-instance-no-public-ip",
     "Do not assign a public IP to instances; reach them through a load balancer or Session Manager.",
     "Instances with public IPs are directly exposed to internet scanning."),
    ("LFT-AWS-EC2-03", "Amazon EC2", "Medium", "Data Protection", "EC2.3",
     "encrypted-volumes",
     "Encrypt attached EBS volumes at rest.",
     "Volume snapshots can expose data if shared or copied."),
    ("LFT-AWS-VPC-01", "Amazon VPC", "High", "Network Security", "EC2.2",
     "vpc-default-security-group-closed",
     "Restrict the default security group so it allows no inbound or outbound traffic.",
     "Resources placed in the default group accidentally become reachable."),
    ("LFT-AWS-VPC-02", "Amazon VPC", "Medium", "Logging", "EC2.6",
     "vpc-flow-logs-enabled",
     "Enable VPC flow logs.",
     "Network-level investigations lack evidence."),

    # ------------------------------------------------------------------ Serverless / data
    ("LFT-AWS-LAMBDA-01", "AWS Lambda", "Critical", "Public Access", "Lambda.1",
     "lambda-function-public-access-prohibited",
     "Do not allow public invocation in the function's resource-based policy.",
     "Anyone could invoke the function and run up cost or reach downstream data."),
    ("LFT-AWS-LAMBDA-02", "AWS Lambda", "Medium", "Posture", "Lambda.2",
     "lambda-function-settings-check",
     "Use a supported runtime and keep it up to date.",
     "Deprecated runtimes stop receiving security patches."),
    ("LFT-AWS-DDB-01", "Amazon DynamoDB", "Medium", "Resilience", "DynamoDB.2",
     "dynamodb-pitr-enabled",
     "Enable point-in-time recovery on tables.",
     "Corrupted or deleted items cannot be restored."),
    ("LFT-AWS-SQS-01", "Amazon SQS", "Medium", "Data Protection", "SQS.1",
     "",
     "Encrypt queues at rest (SqsManagedSseEnabled or a KMS key).",
     "Message payloads are stored unencrypted."),
    ("LFT-AWS-SNS-01", "Amazon SNS", "Medium", "Data Protection", "SNS.1",
     "sns-encrypted-kms",
     "Encrypt topics at rest with a KMS key.",
     "Published messages are stored unencrypted."),
    ("LFT-AWS-KMS-01", "AWS KMS", "Medium", "Data Protection", "KMS.4",
     "cmk-backing-key-rotation-enabled",
     "Enable automatic key rotation for customer managed keys.",
     "Long-lived key material increases the impact of a key compromise."),
    ("LFT-AWS-SM-01", "AWS Secrets Manager", "Medium", "Identity", "SecretsManager.1",
     "secretsmanager-rotation-enabled-check",
     "Enable automatic rotation for secrets.",
     "Static credentials remain valid long after they leak."),

    # ------------------------------------------------------------------ Containers / edge
    ("LFT-AWS-EKS-01", "Amazon EKS", "High", "Network Security", "EKS.1",
     "eks-endpoint-no-public-access",
     "Make the cluster API endpoint private (EndpointPublicAccess false).",
     "A public Kubernetes API endpoint is exposed to credential and vulnerability attacks."),
    ("LFT-AWS-EKS-02", "Amazon EKS", "Medium", "Posture", "EKS.2",
     "eks-cluster-supported-version",
     "Run a supported Kubernetes version and upgrade before end of support.",
     "Unsupported versions miss security fixes."),
    ("LFT-AWS-ECR-01", "Amazon ECR", "Medium", "Posture", "ECR.1",
     "ecr-private-image-scanning-enabled",
     "Enable image scanning on push for private repositories.",
     "Vulnerable images reach production unnoticed."),
    ("LFT-AWS-ELB-01", "Elastic Load Balancing", "Medium", "Data Protection", "ELB.1",
     "alb-http-to-https-redirection-check",
     "Redirect all HTTP listener traffic to HTTPS on Application Load Balancers.",
     "Clients can send data over unencrypted HTTP."),
    ("LFT-AWS-CF-01", "Amazon CloudFront", "Medium", "Data Protection", "CloudFront.3",
     "cloudfront-viewer-policy-https",
     "Require HTTPS between viewers and CloudFront (redirect-to-https or https-only).",
     "Content and cookies travel over plain HTTP."),
    ("LFT-AWS-APIGW-01", "Amazon API Gateway", "Medium", "Logging", "APIGateway.1",
     "api-gw-execution-logging-enabled",
     "Enable execution logging for REST and WebSocket API stages.",
     "API abuse cannot be investigated."),

    # ------------------------------------------------------------------ Account level
    ("LFT-AWS-ACCT-01", "AWS Account", "Critical", "Identity", "IAM.4",
     "iam-root-access-key-check",
     "Do not create access keys for the root user.",
     "Root access keys give unrestricted, hard-to-audit access to the whole account."),
    ("LFT-AWS-ACCT-02", "AWS Account", "Critical", "Identity", "IAM.6",
     "root-account-hardware-mfa-enabled",
     "Protect the root user with hardware MFA.",
     "A phished root password means full account takeover."),
    ("LFT-AWS-ACCT-03", "AWS Account", "High", "Logging", "CloudTrail.1",
     "multi-region-cloudtrail-enabled",
     "Enable a multi-Region CloudTrail trail that records management events.",
     "Control-plane changes cannot be investigated."),
    ("LFT-AWS-ACCT-04", "AWS Account", "High", "Posture", "GuardDuty.1",
     "guardduty-enabled-centralized",
     "Enable Amazon GuardDuty in every Region you use.",
     "Threats such as credential exfiltration and crypto-mining go undetected."),
]


def _rows(csp: str, controls: list, service_map: dict, benchmark_prefix: str) -> list[dict]:
    rows = []
    seen = set()
    for control_id, service, severity, theme, benchmark, policy, recommendation, risk in controls:
        if control_id in seen:
            raise SystemExit(f"Duplicate control id: {control_id}")
        if service not in service_map:
            raise SystemExit(f"{control_id}: service '{service}' is not in service_map.json ({csp})")
        seen.add(control_id)
        scope = service_map[service].get("scope", "resource")
        rows.append({
            "csp": csp,
            "service": service,
            "control_id": control_id,
            "layer": "Platform" if scope == "environment" else "Resource",
            "theme": theme,
            "severity": severity,
            "benchmark": f"{benchmark_prefix} {benchmark}",
            "policy": policy,
            "risk": risk,
            "recommendation": recommendation,
            "user_actionable": True,
        })
    return rows


def main() -> None:
    service_map = json.loads(SERVICE_MAP.read_text(encoding="utf-8"))
    catalog = {
        "AZURE": _rows("AZURE", CONTROLS, service_map["AZURE"], "MCSB"),
        "AWS": _rows("AWS", AWS_CONTROLS, service_map["AWS"], "AWS FSBP"),
    }
    OUT.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(catalog['AZURE'])} Azure and {len(catalog['AWS'])} AWS controls to {OUT}")


if __name__ == "__main__":
    main()
