"""
Copy the five agent system prompts from agents/create_agents.py into
backend/app/agents/prompts.py so every provider (OpenAI, Azure OpenAI, local
OpenAI-compatible servers, Azure AI Foundry) runs the same instructions.

Run after editing an agent's instructions:

    python scripts/sync_agent_prompts.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "agents" / "create_agents.py"
TARGET = ROOT / "backend" / "app" / "agents" / "prompts.py"
AGENT_TYPES = ["orchestrator", "iac_generator", "azure_docs", "security_advisor", "validation", "aws_iac_generator"]

HEADER = '''"""System prompts for the Liftoff agents.

Generated by scripts/sync_agent_prompts.py from agents/create_agents.py - edit
the instructions there and re-run the script. The backend uses these prompts
directly when talking to a chat model (OpenAI, Azure OpenAI, or any
OpenAI-compatible endpoint); on Azure AI Foundry the same text is installed as
the agents' instructions, so behaviour is identical across providers.
"""

SYSTEM_PROMPTS: dict[str, str] = {
'''


def extract(src: str, key: str) -> str:
    """Return the triple-quoted instructions string for one agent key."""
    start = src.index(f'\n    "{key}": {{\n')
    marker = '"instructions": """'
    begin = src.index(marker, start) + len(marker)
    end = src.index('"""', begin)
    return src[begin:end]


def main() -> None:
    src = SOURCE.read_text(encoding="utf-8")
    parts = [HEADER]
    for key in AGENT_TYPES:
        body = extract(src, key).replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        parts.append(f'    "{key}": """{body}""",\n')
    parts.append("}\n")
    TARGET.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"Wrote {len(AGENT_TYPES)} prompts to {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
